POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Instant Pot Chicken Breast",
  "author": "Stephanie",
  "url": "https://iamafoodblog.com/instant-pot-chicken-breast/",
  "likes": 0
}